### ISSUE TITLE
Include LICENSE and Citation files in this repository.

### ISSUE THREAD

**Issue by DevasenaInupakutika** [softwaresaved/fat#148]
Hi Raniere,

We need to include LICENSE and Citation files in this repository. I can include them and push into the repository after you all have a look at it. What do you say?

**Comment by rgaiacs** [comment]
> We need to include LICENSE and Citation files in this repository.

I thought that I had add the LICENSE. :-( My mistake.

> I can include them and push into the repository after you all have a look at it.

Please do it.

**Comment by DevasenaInupakutika** [comment]
[LICENSE](https://github.com/softwaresaved/fat/blob/master/LICENSE) is included.

**Comment by rgaiacs** [comment]
@DevasenaInupakutika Thanks!
