### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by gperu** [softwaresaved/fat#29]
We need the possibility of producing reports.

Initially, it will be sufficient to generate quantitative reports on the use of the Fellowship funds by single fellow, group of fellows (e.g., inauguration year), period of time, etc.

In the future we might want to add more type of reports.

**Comment by rgaiacs** [comment]
Work in progress at https://github.com/softwaresaved/fellowms/tree/report.

**Comment by rgaiacs** [comment]
I'm closing this and we will re-open it later with clear tasks.
