### ISSUE TITLE
Event request: split into sections

### ISSUE THREAD

**Issue by gperu** [softwaresaved/fat#47]

**Comment by rgaiacs** [comment]
Check https://django-floppyforms.readthedocs.io/

**Comment by rgaiacs** [comment]
@gperu and @shoaibsufi Preview:

![screencapture-localhost-8000-fund-1470842907551](https://cloud.githubusercontent.com/assets/1506457/17559840/89740ddc-5f17-11e6-9b52-af4204f7fa47.png)
